Created an interface to get the app profile and file name from application using the SPAN framework
americanexpress/SPAN pull request #2
Opened 2020-12-02 18:03 UTC by nikhilpious1

- updated test cases
- added test cases to validate new changes.

2020-12-02 18:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/americanexpress/SPAN?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/americanexpress/SPAN?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/americanexpress/SPAN?pullRequest=2) it.</sub>

2020-12-02 18:10 UTC, nikhilpious1 commented on src/test/java/com/americanexpress/span/core/database/comptest/SPExecutorCompTest.java
> +        assertEquals(inputObject.getInTimestamp().truncatedTo(ChronoUnit.SECONDS), outputObject.getOutTimestamp().truncatedTo(ChronoUnit.SECONDS));
I was getting assertion Error ( please see below) due to mismatch in milliseconds. Thus I used truncatedTo seconds.

java.lang.AssertionError: 
Expected :2020-12-02T12:40:23.670348800
Actual   :2020-12-02T12:40:23.670348
<Click to see difference>

2020-12-02 20:07 UTC, nikhilpious1 commented on src/main/java/com/americanexpress/span/utility/PropertyConfiguration.java
> +    String getAppProfile();
I made it as functional interface so if application which uses this framework can use lambda expression if it want to only pass the profile. Main purpose of this was less coding for app team.

2020-12-07 21:40 UTC, shailendrasoni02 requested changes
Can you please review

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/core/SPANInitialization.java
> +    private static PropertyConfiguration propertyConfiguration= null;
can you create with default behavior, like just new PropertyConfiguration(){}. If not then, just have inline class and implement this interface and initialized with it.

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/core/SPANInitialization.java
> +        if (Objects.nonNull(propertyConfiguration) && StringUtils.isNotEmpty(propertyConfiguration.getAppProfile())) {
if propertyConfiguration initalized with default then you do not need to check nonnull.

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/core/SPANInitialization.java
> -        String envProperty = SPANUtility.getEnvProperty(APP_PROFILE).orElse(SPANConstants.EMPTY_STRING);
instead of APP_PROFILE, you need use propertyConfiguration.getAppProfile()

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/utility/PropertyConfiguration.java
> +    String getAppProfile();
Good.

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/utility/PropertyConfiguration.java
> +    String getAppProfile();
getAppProfile - It should be getAppProfileEnvVariable and it should be default as discussed. and it should be return APP_PROFILE.

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/utility/PropertyConfiguration.java
> +        return SPANConstants.EMPTY_STRING;
It should be return DEFAULT_FILE_NAME = "SPANConfig";

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/main/java/com/americanexpress/span/codegenerator/SPANCodeGenerator.java
> +                    public String getAppProfile() { return null;}
dont override it.

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/test/java/com/americanexpress/span/constants/SPANTestConstants.java
> +public class SPANTestConstants {
Why we need this file?

2020-12-07 21:40 UTC, shailendrasoni02 commented on src/test/java/com/americanexpress/span/core/ConfigurationValidationTest.java
> +            public String getAppProfile() { return SPANTestConstants.EMPTY_STRING;}
As I said, if you do not wan to provide env variable then you do not need to implement it.

2020-12-11 20:31 UTC, closed without merging